name: Build DFRoot KO for MIUI Camellia

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout DFRoot
        uses: actions/checkout@v4

      - name: Set up Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bc bison flex libssl-dev libelf-dev git gcc-aarch64-linux-gnu

      - name: Clone MIUI Kernel Source
        run: |
          git clone --depth=1 -b camellia-t-oss https://github.com/MiCode/Xiaomi_Kernel_OpenSource.git kernel

      - name: Build DFRoot Module
        run: |
          
